name: Push test
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: apt get install python3
      - name: Run python unit tests
        run: python3 test.py
